### ISSUE TITLE
Optional Chaining support

### ISSUE THREAD

**Issue by rwproj** [standard-things/esm#866]
with latest node (13.8.0) 
```
// example.js
let a
a?.b
```
works with when running `node --harmony`
but

// example.js
import path from 'path'
let a
a?.b
```
`node --harmony -r esm example.js` doesnot work  😢

**Comment by DaniloBarros** [comment]
Are there any updates on this issue?

**Comment by Taranys** [comment]
Some update on this issue, I tried on the last NodeJS version (14.1.0) because you don't need `--harmony` flag anymore. But it still not working :disappointed: 

Without esm, optional chaining works fine.

**Comment by markamccann** [comment]
This is too bad. Same problem with nullish coalescing in Node 14+

**Comment by brettz9** [comment]
FWIW, until esm may support it, it's working for me to use `@babel/register` with the plugin `@babel/plugin-proposal-optional-chaining` (and I also needed the plugin `babel-plugin-transform-import-meta` for `import.meta.url` which, unlike esm, babel/register doesn't understand as well as `babel-plugin-transform-async-to-promises` to avoid regenerator-runtime for async).

**Comment by SamuraiJack** [comment]
Just stumbled on this issue too. Looking forward for the fix.

**Comment by twixr** [comment]
Same issue.
```
id: options.params?.id
                   ^
SyntaxError: Invalid or unexpected token
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
```

The reason I use esm is so that I don't have to build my code using Babel. So using babel plugins isn't an option for me.

**Comment by jdalton** [comment]
I'll update the parser. Thanks!

**Comment by matthewharwood** [comment]
@jdalton will this parser update include nullish coalescing? 🙏

**Comment by hroland** [comment]
@jdalton Excited for this one!

**Comment by matthewharwood** [comment]
@jdalton Any update on when we can expect this?

**Comment by jsg2021** [comment]
It works after updating acorn.

**Comment by matthewharwood** [comment]
> It works after updating acorn.

Ayeee! You the bes!

if you want this sooner than later and ya'll are using yarn.
```
  "resolutions": {
    "acorn": "^7.3.1"
  },
```

**Comment by prashantpalikhe** [comment]
Awesome! Hope this gets released soon 👍

**Comment by patspam** [comment]
Any ETA on this?

**Comment by jsg2021** [comment]
It's fixed in my PR. #883

You can use it or fork it. I'm not a maintainer, so I can't merge/publish.

**Comment by luluhoc** [comment]
Can you please update the parser?

**Comment by jsg2021** [comment]
@luluhoc there is a PR waiting to merge.

**Comment by hroland** [comment]
We've been using @jsg2021's PR in production for 4 months now without an issue! 🙌

**Comment by matthieusieben** [comment]
> `esm` is the world’s most advanced ECMAScript module loader.

You can't just pretend that and have this issue still un-resolved...

**Comment by chrisspiegl** [comment]
May be considered #offtopic: but how is this not supported yet? Please, pretty please merge the PR as it seems to be working for many.

**Comment by loilo** [comment]
@chrisspiegl Maybe [this](https://twitter.com/jdalton/status/1362880981569568770) does answer your question. 😉

**Comment by aksel** [comment]
> @chrisspiegl Maybe [this](https://twitter.com/jdalton/status/1362880981569568770) does answer your question. wink

Far out.

So esm does not have a maintainer?

**Comment by twelve17** [comment]
> So esm does not have a maintainer?

If the recent activity is an indicator, looks like the parachute landed in the Salesforce jungle  😉

**Comment by CleyFaye** [comment]
I believe it's worth noting that ECMAScript modules support is now considered "stable" in node 16, and after a quick glance seems like using esm would be redundant (that is, if you can blindly upgrade to node16).

**Comment by twelve17** [comment]
@CleyFaye indeed. Though my main hangup is testing with mocks.

**Comment by canonic-epicure** [comment]
More over, EcmaModules support is available in Node 12 already

**Comment by chrisspiegl** [comment]
That seems true that with V12+ and especially with V16, you have pretty good support for ECMAScript modules.
However, the ESM module here gave a lot more 'leeway'. Moving to a clean implementation was a good chunk of work for me, but at this point I got rid of ESM in my code base at least.

**Comment by smcenlly** [comment]
We needed this issue fixed so have [forked](https://github.com/wallabyjs/esm) and [published our forked repo](https://www.npmjs.com/package/esm-wallaby) if anyone needs it.

**Comment by jdalton** [comment]
Ah wallaby! @smcenlly. I should revisit this stuff.

**Comment by alcalawil** [comment]
This code fails. Any import word found in the code will make it fail:

`node -r esm script.js`
```
// import smart things from china
const xx = process?.version; console.log(xx)
```

**Comment by toastyghost** [comment]
Fix in PR _a year and a half ago_ and STILL not merged?

**Comment by chrisspiegl** [comment]
@toastyghost As others have pointed out, we should consider this project dead until proven differently.
So it'd be best to move forward and not depend on `esm` any more if at all possible.
All things considered: Node has come pretty far and is now supporting most of the ESM features natively (if you are able to update to the latest releases).

**Comment by canonic-epicure** [comment]
Yup, native ES modules support was added in Node 12.~20

**Comment by flopail** [comment]
Hi everyone,
:)

I had the same problem about optional chaining operator (with node >= 14 ) when I did: `node -r esm path/to/my/file.js`
I solve it by installing esm-wallaby dependency and by using it like this: `node -r esm-wallaby path/to/my/file.js`

In my case, it also fixes nullish coalescing operator  (`??`). 

I hope it could help.
Have a good day!

**Comment by Slapbox** [comment]
Node's support for built-in modules is still god-awful. You have to jump through all sorts of hoops and define things at the project level to get them to work. I'd really like to have optional chaining support with `node -r esm`

**Comment by CleyFaye** [comment]
Can you elaborate on this? As far as I know, you only need either setting "type: module" in your package.json or name your files .mjs, both options providing great compatibility with all the tooling around (like bundlers).
I'm curious at what other troubles can arise at this point.

**Comment by Slapbox** [comment]
Some tooling doesn't do well with `type: module` and having to rename all of your files to `.mjs` is sort of madness, no? Not to mention that things like `import * from './foo'` will work if the file is `foo.js` but will fail if it's `foo.mjs` with all the tooling I've used so far. I'm sure that's not universal, but it makes a lot of headaches.

**Comment by CleyFaye** [comment]
I see. I didn't encounter any situation that needed renaming everything; most bundler just accept whatever you throw at them, and not having the full file name is not really on the table either.

But I see how some workflow might require that. Still, it is likely that `esm` never gets an upgrade. It might be wiser to look into updating these tools too.
